server:
  port: 8081

# Test
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    
# dev 환경
---
spring:
  profiles: dev

# real 환경
---
spring:
  profiles: real